In [1]:
import pandas as pd
import numpy as np

In [2]:
COLS_TO_REMOVE = [
    # слабо связаны с ценой
    'WoodDeckSF', '2ndFlrSF', 'OpenPorchSF', 'HalfBath',
    'LotArea', 'BsmtFullBath', 'BsmtUnfSF', 'BedroomAbvGr', 'ScreenPorch',
    'PoolArea', 'MoSold', '3SsnPorch', 'BsmtFinSF2', 'BsmtHalfBath',
    'MiscVal', 'Id', 'LowQualFinSF', 'YrSold', 'OverallCond', 'MSSubClass',
    'EnclosedPorch', 'KitchenAbvGr',
    # дублируют другие признаки
    '1stFlrSF', 'TotRmsAbvGrd', 'GarageCars',
    # исходная цена: вместо неё будет LogSalePrice
    'SalePrice',
    # пропущено больше 70% значений
    'PoolQC', 'MiscFeature', 'Alley', 'Fence',
]

COLS_TO_REMOVE_TEST = [
    # слабо связаны с ценой (Id в test оставляем: он нужен для сабмита)
    'WoodDeckSF', '2ndFlrSF', 'OpenPorchSF', 'HalfBath',
    'LotArea', 'BsmtFullBath', 'BsmtUnfSF', 'BedroomAbvGr', 'ScreenPorch',
    'PoolArea', 'MoSold', '3SsnPorch', 'BsmtFinSF2', 'BsmtHalfBath',
    'MiscVal', 'LowQualFinSF', 'YrSold', 'OverallCond', 'MSSubClass',
    'EnclosedPorch', 'KitchenAbvGr',
    # дублируют другие признаки
    '1stFlrSF', 'TotRmsAbvGrd', 'GarageCars',
    # пропущено больше 70% значений
    'PoolQC', 'MiscFeature', 'Alley', 'Fence',
]

In [ ]:
data = pd.read_csv('../data/raw/train.csv')
data['LogSalePrice'] = np.log1p(data['SalePrice'])
print(data.shape)
data.head()

(1460, 82)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LogSalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,12.247699
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,12.109016
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,12.317171
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,11.849405
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,12.429220

In [4]:
test_data = pd.read_csv('../data/raw/test.csv')
print(test_data.shape)
test_data.head()

(1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
data.drop(columns=COLS_TO_REMOVE, inplace=True)
print(data.shape)
data.info()

(1460, 52)
<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 52 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   str
 1   LotFrontage    1201 non-null   float64
 2   Street         1460 non-null   str
 3   LotShape       1460 non-null   str
 4   LandContour    1460 non-null   str
 5   Utilities      1460 non-null   str
 6   LotConfig      1460 non-null   str
 7   LandSlope      1460 non-null   str
 8   Neighborhood   1460 non-null   str
 9   Condition1     1460 non-null   str
 10  Condition2     1460 non-null   str
 11  BldgType       1460 non-null   str
 12  HouseStyle     1460 non-null   str
 13  OverallQual    1460 non-null   int64
 14  YearBuilt      1460 non-null   int64
 15  YearRemodAdd   1460 non-null   int64
 16  RoofStyle      1460 non-null   str
 17  RoofMatl       1460 non-null   str
 18  Exterior1st    1460 non-null   str
 19  Exterior2nd    1460 non-null   str
 20  MasVnrType     588 non-null    str
 21  MasVnrArea     1452 non-null   float64
 22  ExterQual      1460 non-null   str
 23  ExterCond      1460 non-null   str
 24  Foundation     1460 non-null   str
 25  BsmtQual       1423 non-null   str
 26  BsmtCond       1423 non-null   str
 27  BsmtExposure   1422 non-null   str
 28  BsmtFinType1   1423 non-null   str
 29  BsmtFinSF1     1460 non-null   int64
 30  BsmtFinType2   1422 non-null   str
 31  TotalBsmtSF    1460 non-null   int64
 32  Heating        1460 non-null   str
 33  HeatingQC      1460 non-null   str
 34  CentralAir     1460 non-null   str
 35  Electrical     1459 non-null   str
 36  GrLivArea      1460 non-null   int64
 37  FullBath       1460 non-null   int64
 38  KitchenQual    1460 non-null   str
 39  Functional     1460 non-null   str
 40  Fireplaces     1460 non-null   int64
 41  FireplaceQu    770 non-null    str
 42  GarageType     1379 non-null   str
 43  GarageYrBlt    1379 non-null   float64
 44  GarageFinish   1379 non-null   str
 45  GarageArea     1460 non-null   int64
 46  GarageQual     1379 non-null   str
 47  GarageCond     1379 non-null   str
 48  PavedDrive     1460 non-null   str
 49  SaleType       1460 non-null   str
 50  SaleCondition  1460 non-null   str
 51  LogSalePrice   1460 non-null   float64
dtypes: float64(4), int64(9), str(39)
memory usage: 593.3 KB

In [ ]:
missing = data.isna().sum().index
missing

Index(['MSZoning', 'LotFrontage', 'Street', 'LotShape', 'LandContour',
       'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1',
       'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'YearBuilt',
       'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd',
       'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir',
       'Electrical', 'GrLivArea', 'FullBath', 'KitchenQual', 'Functional',
       'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'SaleType', 'SaleCondition', 'LogSalePrice'],
      dtype='str')

In [7]:
test_data.drop(columns=COLS_TO_REMOVE_TEST, inplace=True)
print(test_data.shape)
test_data.info()

(1459, 52)
<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 52 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSZoning       1455 non-null   str
 2   LotFrontage    1232 non-null   float64
 3   Street         1459 non-null   str
 4   LotShape       1459 non-null   str
 5   LandContour    1459 non-null   str
 6   Utilities      1457 non-null   str
 7   LotConfig      1459 non-null   str
 8   LandSlope      1459 non-null   str
 9   Neighborhood   1459 non-null   str
 10  Condition1     1459 non-null   str
 11  Condition2     1459 non-null   str
 12  BldgType       1459 non-null   str
 13  HouseStyle     1459 non-null   str
 14  OverallQual    1459 non-null   int64
 15  YearBuilt      1459 non-null   int64
 16  YearRemodAdd   1459 non-null   int64
 17  RoofStyle      1459 non-null   str
 18  RoofMatl       1459 non-null   str
 19  Exterior1st    1458 non-null   str
 20  Exterior2nd    1458 non-null   str
 21  MasVnrType     565 non-null    str
 22  MasVnrArea     1444 non-null   float64
 23  ExterQual      1459 non-null   str
 24  ExterCond      1459 non-null   str
 25  Foundation     1459 non-null   str
 26  BsmtQual       1415 non-null   str
 27  BsmtCond       1414 non-null   str
 28  BsmtExposure   1415 non-null   str
 29  BsmtFinType1   1417 non-null   str
 30  BsmtFinSF1     1458 non-null   float64
 31  BsmtFinType2   1417 non-null   str
 32  TotalBsmtSF    1458 non-null   float64
 33  Heating        1459 non-null   str
 34  HeatingQC      1459 non-null   str
 35  CentralAir     1459 non-null   str
 36  Electrical     1459 non-null   str
 37  GrLivArea      1459 non-null   int64
 38  FullBath       1459 non-null   int64
 39  KitchenQual    1458 non-null   str
 40  Functional     1457 non-null   str
 41  Fireplaces     1459 non-null   int64
 42  FireplaceQu    729 non-null    str
 43  GarageType     1383 non-null   str
 44  GarageYrBlt    1381 non-null   float64
 45  GarageFinish   1381 non-null   str
 46  GarageArea     1458 non-null   float64
 47  GarageQual     1381 non-null   str
 48  GarageCond     1381 non-null   str
 49  PavedDrive     1459 non-null   str
 50  SaleType       1458 non-null   str
 51  SaleCondition  1459 non-null   str
dtypes: float64(6), int64(7), str(39)
memory usage: 592.8 KB

In [8]:
NONE_COLS = ['MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
             'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']
ZERO_COLS = ['MasVnrArea', 'BsmtFinSF1', 'TotalBsmtSF', 'GarageArea']

for df in (data, test_data):
    df[NONE_COLS] = df[NONE_COLS].fillna('None')
    df[ZERO_COLS] = df[ZERO_COLS].fillna(0)
    # Нет гаража -> год постройки дома (0 был бы выбросом среди годов ~1900-2010)
    df['GarageYrBlt'] = df['GarageYrBlt'].fillna(df['YearBuilt'])

In [9]:
# LotFrontage: медиана по району (у соседних домов похожая ширина участка)
lot_medians = data.groupby('Neighborhood')['LotFrontage'].median()
for df in (data, test_data):
    df['LotFrontage'] = df['LotFrontage'].fillna(df['Neighborhood'].map(lot_medians))

# Остальные категориальные (MSZoning, Electrical, KitchenQual, SaleType, ...): мода из train
cat_cols = data.select_dtypes(exclude='number').columns
modes = data[cat_cols].mode().iloc[0]
data[cat_cols] = data[cat_cols].fillna(modes)
test_data[cat_cols] = test_data[cat_cols].fillna(modes)

print('NaN в train:', data.isna().sum().sum(), '| NaN в test:', test_data.isna().sum().sum())

NaN в train: 0 | NaN в test: 0

In [10]:
# 'None' значит «нет объекта» (нет подвала, гаража), поэтому он получает 0
QUAL_MAP = {'None': 0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}
FIN_TYPE_MAP = {'None': 0, 'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6}

ORDINAL_MAPS = {
    'ExterQual': QUAL_MAP,
    'ExterCond': QUAL_MAP,
    'BsmtQual': QUAL_MAP,
    'BsmtCond': QUAL_MAP,
    'HeatingQC': QUAL_MAP,
    'KitchenQual': QUAL_MAP,
    'FireplaceQu': QUAL_MAP,
    'GarageQual': QUAL_MAP,
    'GarageCond': QUAL_MAP,
    'BsmtExposure': {'None': 0, 'No': 1, 'Mn': 2, 'Av': 3, 'Gd': 4},
    'BsmtFinType1': FIN_TYPE_MAP,
    'BsmtFinType2': FIN_TYPE_MAP,
    'GarageFinish': {'None': 0, 'Unf': 1, 'RFn': 2, 'Fin': 3},
    'Functional': {'Sal': 0, 'Sev': 1, 'Maj2': 2, 'Maj1': 3, 'Mod': 4, 'Min2': 5, 'Min1': 6, 'Typ': 7},
    'CentralAir': {'N': 0, 'Y': 1},
    'PavedDrive': {'N': 0, 'P': 1, 'Y': 2},
}

# заменяем текст на числа по словарю
for df in (data, test_data):
    for col, mapping in ORDINAL_MAPS.items():
        df[col] = df[col].map(mapping)

In [11]:
nominal_cols = data.select_dtypes(exclude='number').columns
print(f'Nominal features: {len(nominal_cols)}')

data = pd.get_dummies(data, columns=nominal_cols, dtype=int)
test_data = pd.get_dummies(test_data, columns=nominal_cols, dtype=int)

# В test могут не встретиться некоторые категории из train (и наоборот),
# поэтому выравниваем колонки test по train: недостающие заполняем нулями, лишние удаляем.
# LogSalePrice есть только в train, Id только в test
feature_cols = data.columns.drop('LogSalePrice')
test_data = test_data.reindex(columns=['Id', *feature_cols], fill_value=0)

Nominal features: 23

In [ ]:
print(data.shape, test_data.shape)
print('NaN в train:', data.isna().sum().sum(), '| NaN в test:', test_data.isna().sum().sum())
print('Нечисловых колонок:', len(data.select_dtypes(exclude='number').columns))

(1460, 197) (1459, 197)
NaN в train: 0 | NaN в test: 0
Нечисловых колонок: 0

In [13]:
CONTINUOUS_COLS = ['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'TotalBsmtSF', 'GrLivArea', 'GarageArea']

skew_before = data[CONTINUOUS_COLS].skew()
skew_after = np.log1p(data[CONTINUOUS_COLS]).skew()

# Логарифмируем, только если признак скошен и логарифм реально уменьшает скошенность.
# Например, у TotalBsmtSF есть нули (нет подвала): после log1p они становятся выбросами слева
log_cols = skew_before[(skew_before > 0.75) & (skew_after.abs() < skew_before.abs())].index

print(pd.DataFrame({'before': skew_before, 'after_log': skew_after}).round(2))
print('\nLog-transformed:', list(log_cols))

for df in (data, test_data):
    df[log_cols] = np.log1p(df[log_cols])

             before  after_log
LotFrontage    2.21      -0.91
MasVnrArea     2.68       0.50
BsmtFinSF1     1.69      -0.62
TotalBsmtSF    1.52      -5.15
GrLivArea      1.37      -0.01
GarageArea     0.18      -3.48

Log-transformed: ['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'GrLivArea']

In [14]:
# Масштабируем все небинарные признаки (площади, годы, ordinal-оценки); one-hot колонки 0/1 не трогаем
scale_cols = [col for col in feature_cols if data[col].nunique() > 2]
print(f'Scaled features: {len(scale_cols)}')

means = data[scale_cols].mean()
stds = data[scale_cols].std()

data[scale_cols] = (data[scale_cols] - means) / stds
test_data[scale_cols] = (test_data[scale_cols] - means) / stds

data[scale_cols].describe().loc[['mean', 'std']].round(2)

Scaled features: 27

,LotFrontage,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,...,KitchenQual,Functional,Fireplaces,FireplaceQu,GarageYrBlt,GarageFinish,GarageArea,GarageQual,GarageCond,PavedDrive
mean,-0.0,0.0,0.0,0.0,0.0,-0.0,0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,0.0,0.0,-0.0
std,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [ ]:
import os

os.makedirs('../data/processed', exist_ok=True)

data.to_csv('../data/processed/train.csv', index=False)
test_data.to_csv('../data/processed/test.csv', index=False)